spring.datasource.url: jdbc:${CLEARDB_DATABASE_URL:mysql://localhost:3306/thesis?useSSL=false&serverTimezone=UTC}
spring.datasource.username: root
spring.datasource.password: testtest
spring.jpa.hibernate.ddl-auto: validate
spring.jpa.properties.hibernate.dialect: org.hibernate.dialect.MySQL8Dialect
server.port: ${PORT:8080}

blog.title: MoviePub
blog.subtitle: Отзывы о фильмах
blog.phone: +7 903 555-55-55
blog.email: movie@mail.ru
blog.copyright: Квентин Тарантино
blog.copyrightFrom: 1991

spring.mail.host: ${MAIL_HOST:smtp.mailtrap.io}
spring.mail.port: ${SMTP_PORT:2525}
spring.mail.username: ${LOGIN:e814c71ebd0bc0}
spring.mail.password: ${PASSWORD:634dc3bf27b195}
