spring.datasource.url: jdbc:mysql://localhost:3306/thesis?useSSL=false&serverTimezone=UTC
spring.datasource.username: root
spring.datasource.password: testtest
spring.jpa.hibernate.ddl-auto: validate

spring.liquibase.change-log: classpath:db/changelog/db.changelog-master-1.0.yaml
upload.path: D://SkillBox/Diploma/data/upload/ab/cd/ef

blog.title: MoviePub
blog.subtitle: Отзывы о фильмах
blog.phone: +7 903 555-55-55
blog.email: movie@mail.ru
blog.copyright: Квентин Тарантино
blog.copyrightFrom: 1991
