spring.datasource.url: jdbc:mysql://localhost:3306/thesis?useSSL=false&serverTimezone=UTC
spring.datasource.username: root
spring.datasource.password: testtest
spring.jpa.hibernate.ddl-auto: validate

spring.liquibase.change-log: classpath:db/changelog/db.changelog-master-1.0.yaml
